export const projects = [
  {
    slug: 'nova-finance-platform',
    title: 'Nova Finance Platform',
    description: 'A comprehensive wealth management suite handling over $2B in monthly transactions with real-time analytics.',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800',
    tags: ['FINTECH', 'WEB APP'],
    overview: 'Nova was built to bridge the gap between amateur finance tracking and professional data analysis. Over a six-month period, we developed a cross-platform solution that integrates seamlessly with existing banking infrastructure.',
    problem: 'Most finance apps either provide too little data or overwhelm the user with charts that lack context. Users reported difficulty understanding how their spending patterns directly impacted their savings goals.',
    solution: 'We introduced a unified dashboard with a single "Financial Health Score" that synthesizes spending, savings, and investment data into one actionable metric, with progressive disclosure for power users.',
    techStack: ['React Native', 'Firebase', 'GraphQL', 'Node.js'],
    platforms: ['iOS', 'Android'],
    liveLink: 'https://example.com',
    appStoreLink: null,
    screens: [
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
      'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800',
      'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=400',
      'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800',
    ],
  },
  {
    slug: 'pulse-fitness-tracker',
    title: 'Pulse Fitness Tracker',
    description: 'Precision health monitoring app for elite athletes.',
    image: 'https://images.unsplash.com/photo-1576678927484-cc907957088c?w=800',
    tags: ['HEALTH', 'iOS'],
    overview: 'Pulse was built to bridge the gap between amateur fitness tracking and professional athletic data analysis. The goal was to create an intuitive interface that simplifies complex biometric data into actionable daily goals.',
    problem: 'Most fitness apps either provide too little data or overwhelm the user with charts that lack context. Users reported notification fatigue and a lack of motivation.',
    solution: 'We introduced the Daily Readiness Score — a single metric that synthesizes heart rate variability, sleep duration, and recent activity into one number.',
    techStack: ['React Native', 'Firebase', 'GraphQL', 'Node.js'],
    platforms: ['iOS', 'Android'],
    liveLink: null,
    appStoreLink: 'https://apps.apple.com',
    screens: [
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
      'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800',
      'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=400',
      'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800',
    ],
  },
  {
    slug: 'vertex-cloud-suite',
    title: 'Vertex Cloud Suite',
    description: 'Next-gen infrastructure management for devops teams.',
    image: 'https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800',
    tags: ['SAAS', 'DESKTOP'],
    overview: 'Vertex was designed for devops teams managing complex multi-cloud infrastructure. Built as a desktop-first experience with web fallback.',
    problem: 'Existing tools required switching between multiple dashboards and CLI tools, causing context switching and human error in production environments.',
    solution: 'A unified control plane that aggregates all cloud providers, CI/CD pipelines, and monitoring into a single desktop application with keyboard-first navigation.',
    techStack: ['Electron', 'React', 'Node.js', 'PostgreSQL'],
    platforms: ['Windows', 'macOS', 'Linux'],
    liveLink: 'https://example.com',
    appStoreLink: null,
    screens: [
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
      'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800',
      'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=400',
      'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800',
    ],
  },
  {
    slug: 'orbit-design-system',
    title: 'Orbit Design System',
    description: 'A comprehensive design system used across 12 products and 3 platforms.',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?w=800',
    tags: ['DESIGN', 'WEB'],
    overview: 'Orbit is a full-scale design system built to unify the visual language across 12 products in a growing SaaS company.',
    problem: 'Inconsistent UI patterns across products were slowing down development and confusing users who used multiple products in the suite.',
    solution: 'A token-based design system with Figma components, React component library, and automated design-to-code tooling that reduced UI development time by 60%.',
    techStack: ['React', 'Figma', 'Storybook', 'TypeScript'],
    platforms: ['Web'],
    liveLink: 'https://example.com',
    appStoreLink: null,
    screens: [
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
      'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800',
      'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=400',
      'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800',
    ],
  },
  {
    slug: 'relay-logistics-dashboard',
    title: 'Relay Logistics Dashboard',
    description: 'Real-time fleet tracking and logistics management for enterprise transport companies.',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800',
    tags: ['LOGISTICS', 'WEB APP'],
    overview: 'Relay is an enterprise logistics platform built for transport companies managing hundreds of vehicles across multiple regions.',
    problem: 'Dispatchers were using spreadsheets and phone calls to coordinate fleets, leading to delays, missed deliveries, and no real-time visibility.',
    solution: 'A real-time dashboard with live GPS tracking, automated route optimization, and push notifications for drivers — reducing average delivery time by 23%.',
    techStack: ['Next.js', 'Supabase', 'PostgreSQL', 'Tailwind'],
    platforms: ['Web'],
    liveLink: 'https://example.com',
    appStoreLink: null,
    screens: [
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
      'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800',
      'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=400',
      'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800',
    ],
  },
  {
    slug: 'bloom-ecommerce',
    title: 'Bloom E-Commerce',
    description: 'A full-stack e-commerce platform with AI-powered product recommendations.',
    image: 'https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=800',
    tags: ['E-COMMERCE', 'MOBILE'],
    overview: 'Bloom is a modern e-commerce platform built for a fashion retailer looking to replace their legacy Shopify setup with a fully custom solution.',
    problem: 'The client was losing customers at checkout due to slow load times and a clunky mobile experience on their existing platform.',
    solution: 'A headless commerce architecture with a Next.js storefront, custom recommendation engine, and a React Native mobile app — resulting in a 40% increase in mobile conversions.',
    techStack: ['Next.js', 'React Native', 'Supabase', 'Tailwind'],
    platforms: ['Web', 'iOS', 'Android'],
    liveLink: 'https://example.com',
    appStoreLink: 'https://apps.apple.com',
    screens: [
      'https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?w=400',
      'https://images.unsplash.com/photo-1551650975-87deedd944c3?w=800',
      'https://images.unsplash.com/photo-1555774698-0b77e0d5fac6?w=400',
      'https://images.unsplash.com/photo-1563986768494-4dee2763ff3f?w=800',
    ],
  },
]